notify_dashboard:
    path:     /
    defaults: { _controller: NotifyAppBundle:Dashboard:index }

notify_feedback:
    resource: "@NotifyAppBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedbacks/
