imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: { fallbacks: en }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

nelmio_api_doc: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    encryption: ssl
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    disable_delivery:  false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Notify\UserBundle\Entity\User
    from_email:
        address:        webmaster@example.com
        sender_name:    webmaster

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

rms_push_notifications:
  android:
      timeout: 5 # Seconds to wait for connection timeout, default is 5
      gcm:
          api_key: AIzaSyDGQbqNRvySDLDo8lrXthM0JazYlRHcFLg # This is titled "Server Key" when creating it
          use_multi_curl: true # default is true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            blameable: true
            loggable: true
            uploadable: true
            sluggable: true
            tree: true

mopa_bootstrap:
    form:
        show_legend: false
        horizontal_label_class: ~
        horizontal_input_wrapper_class: ~

gos_web_socket:
    server:
        port: 9090        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
