Notify\AppBundle\Entity\Feedback:
    type: entity
    table: feedback
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            feedback: ''
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        feedback:
            type: string
            nullable: false
            length: 100
            fixed: false
            feedback: ''
            column: feedback
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
           nullable: true
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
           nullable: true
    lifecycleCallbacks: {  }
